import { describe, expect, it } from "vitest";
import cases from "../data/eva-golden.json";
import { simulateEVA } from "./eva";
import type { EVAScenario } from "../types";
import type { EVAOptions } from "./evaContract";

function compare(actual: unknown, expected: unknown): void {
  if (typeof expected === "number") expect(actual).toBeCloseTo(expected, 9);
  else if (Array.isArray(expected)) {
    expect(Array.isArray(actual)).toBe(true);
    expect((actual as unknown[]).length).toBe(expected.length);
    expected.forEach((item, i) => compare((actual as unknown[])[i], item));
  } else if (expected !== null && typeof expected === "object") {
    for (const [key, value] of Object.entries(expected)) compare((actual as Record<string, unknown>)[key], value);
  } else expect(actual).toEqual(expected);
}

describe("Python/browser EVA parity: synthetic reference cases", () => {
  for (const item of cases) it(item.name, () => {
    // Fixtures are generated by scripts/12_export_eva_browser_contract.py.
    const actual = simulateEVA(item.scenario as EVAScenario, item.options as EVAOptions);
    compare(actual, item.expected);
  });
  it.each([NaN, Infinity, -1, 0])("rejects invalid absolute pressure %s", pressure => {
    const scenario = structuredClone(cases[0].scenario) as EVAScenario;
    scenario.suit.pressurePsia = pressure;
    expect(() => simulateEVA(scenario)).toThrow();
  });
  it("rejects a variable-pressure flag without a schedule", () => {
    const scenario = structuredClone(cases[0].scenario) as EVAScenario;
    scenario.suit.variablePressure = true;
    expect(() => simulateEVA(scenario)).toThrow(/schedule/);
  });
  it("rejects malformed workload duration rather than resampling", () => {
    const scenario = structuredClone(cases[0].scenario) as EVAScenario;
    scenario.workload = [{ name: "bad", durationMin: 10, vo2MlKgMin: 5 }];
    expect(() => simulateEVA(scenario)).toThrow(/sum/);
  });
  it("uses PB exercise independently of EVA workload", () => {
    const scenario = structuredClone(cases[2].scenario) as EVAScenario;
    const initial = simulateEVA(scenario);
    scenario.meanVo2MlKgMin = 30;
    scenario.peakVo2MlKgMin = 40;
    expect(simulateEVA(scenario).p1n2Psia).toBe(initial.p1n2Psia);
  });
  it("tolerates segment sum rounding without an uncovered final interval", () => {
    const scenario = structuredClone(cases[1].scenario) as EVAScenario;
    scenario.workload.at(-1)!.durationMin -= 5e-7;
    scenario.pressureSegments!.at(-1)!.durationMin += 5e-7;
    expect(simulateEVA(scenario).timeline.at(-1)?.timeMin).toBe(scenario.evaDurationMin);
  });
});
